version: '3'
services:
  kafka:
    image: confluentinc/cp-kafka:3.0.0
    ports:
      - "9092:9092"
    container_name: kafka-branch
#    network_mode: host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:3.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
#    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
